# Generated by Django 2.0.2 on 2018-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcaddress',
            name='expected_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='btcaddress',
            name='paid_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
